### ISSUE TITLE
Turn off seeder in production

### ISSUE THREAD

**Issue by mtlaney** [USDAForestService/fs-open-forest-platform#1028]
## Notes
* We need to turn off the seederfile in production*

## Acceptance Criteria
- [x] Seederfile is turned off

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
- [x] PO Approved

**Comment by ASprinkle** [comment]
@mtlaney thanks. it's important to get this in right away so that the site doesn't reset tonight. :)

**Comment by JonathanLerner54** [comment]
Please provide more details on what the issue is and why this is needed.  Thanks

**Comment by ASprinkle** [comment]
We need to turn off the seederfile so the x-mas tree cutting area dates/times do not revert to something incorrect. this reduces risk of the site populating inaccurate information. The seederfile is something that needs to be re-worked for efficiencies sake after this pilot season is over. Our team determined during this season's pilot build, that this is something we'll need to address in the future. For purposes of this x-mas tree pilot, we'll need to turn it off so that the dates don't revert at midnight. @mtlaney can provide more technical insight than I can.

**Comment by JonathanLerner54** [comment]
Thanks,
