### ISSUE TITLE
SEO - Create an Effective Site Submission Plan for Christmas Tree Permitting sites

### ISSUE THREAD

**Issue by DawnDesigner** [USDAForestService/fs-open-forest-platform#637]
Create a scale able plan for Search Engine submission to improve search engine ranking for all Christmas Tree permitting sites within the Open Forest system, keeping in mind this system can be used for all future permitting sites within the system.

**Comment by lisamcmichael** [comment]
@ASprinkle and @lisaredux Can you recall what conversations, plans, and/or research has been made with SEO for the Xmas ecommerce site? 

Btw, there is a correlation between SEO and digital accessibility. Google favors sites that are accessible because when pages are crawled for key words, Alt Text is present along with title tags, and so on.  If you search for "Google Lighthouse", you can play around with running reports as often as you'd like.

**Comment by ASprinkle** [comment]
@lisamcmichael I recall only some our brainstorming from our team meeting in April, and the stories that are in New Issues that Dawn created. I'd like to see more refinement of those stories and information prior to bringing them in. I think we've got more work to do for MBS before enhancing the site for SEO.  I do not recall seeing a"plan" or formalized research documentation for the SEO stories, perhaps @lisaredux  does.

**Comment by lisaredux** [comment]
@lisamcmichael To add to what @ASprinkle mentioned, I wasn't that aware of the research that Dawn was doing at the time. Lighthouse seems familiar though. I do remember the problem of why this came up — that googling the key words didn't lead to the Open Forest site. Adding descriptions and metadata in the header usually do a great solution, but not sure what the other plan was or where it lives. I'll dig around after standup

**Comment by ASprinkle** [comment]
@lisamcmichael  ^ thanks for reviewing!
